### PR TITLE
[ISSUE-845] Update contribution guide

### LINKED ISSUE #845: Update Contribution Guide
Currently contribution guide has some misleading information which makes it harder for newbies to figure out how the project works.

### Requirements 
go v1.16 is old version, the version written in `go.mod` is 1.17

### Loading operator image to kind

`make load-operator-image` pulls image from registry, actually we should use `make kind-tag-operator-image` and `make kind-load-operator-image`

```
# Retag CSI images and load them to kind
make kind-tag-images TAG=${CSI_VERSION} REGISTRY=${REGISTRY}
make kind-load-images TAG=${CSI_VERSION} REGISTRY=${REGISTRY}
make load-operator-image OPERATOR_VERSION=${CSI_OPERATOR_VERSION} REGISTRY=${REGISTRY}
```

### Validation

The "./test" directory was renamed to "./tests"

```
# Install test app
cd ${CSI_BAREMETAL_DIR}
kubectl apply -f test/app/nginx.yaml
```

### PR DESCRIPTION
**Pull request by aaletov**
### Resolves #845  

Updated Contribution Guide

## PR checklist
- [x] Add link to the issue
- [x] Choose Project
- [x] Choose PR label
- [ ] New unit tests added
- [ ] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

## Testing
_Provide test details_

### CODE REVIEW

**Comment by safronovD** [comment]
+ https://github.com/dell/csi-baremetal/issues/798

**Comment by safronovD** [comment]
Resolves #845

**Comment by safronovD** [comment]
@aaletov please, add also the valid link in `use devkit` section - https://github.com/dell/csi-baremetal/blob/master/devkit/README.md

**Comment by aaletov** [comment]
@safronovD Done

**Comment by AnnaDutova** [comment]
Hi @aaletov please, sign your commits for passing DCO test

**Review by mitsaa — APPROVED** [review]

**Review by yurkov-anton — APPROVED** [review]

**Review by misanthropicat — APPROVED** [review]

**Pull request merged**
