### PR TITLE
[ISSUE-626] e2e test skipped on master

### LINKED ISSUE #626: Baremetal csi tests on GitHub Actions
Need to create GitHub Actions script to perform CSI Baremetal CI tests and found a way to run them after creating issue comment from an open Pull Request. After success completion, it’s better to have an opportunity to see output results.

### PR DESCRIPTION
**Pull request by mishoyama**
### Resolves #626

E2E tests skipped on master since we check pull_request and comment only.

## PR checklist
- [x] Add link to the issue
- [x] Choose Project
- [x] Choose PR label
- [ ] New unit tests added
- [x] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

## Testing
Tests on fork:
1. Push on master - https://github.com/mishoyama/csi-baremetal/actions/runs/1549693455
2. PR validation - https://github.com/mishoyama/csi-baremetal/actions/runs/1549741930

### CODE REVIEW

**Comment by mishoyama** [comment]
test

**Review by safronovD — APPROVED** [review]

**Comment by mishoyama** [comment]
test 2

**Comment by mishoyama** [comment]
ci

**Review by yurkov-anton — APPROVED** [review]

**Comment by mishoyama** [comment]
test

**Pull request merged**
